### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by stagas** [DataStrategist/Musical-chord-progressions#1]
Great work! I'd like to ask what is the license to reuse that data? Can you add one in the repo?

**Comment by DataStrategist** [comment]
In fact, I don't know the license hooktheory uses! I asked them, will create one soon as I hear back. In the meantime, I'm leaning towards GPL2

**Comment by DataStrategist** [comment]
Hrm... no one is giving any hints there, and it's not posted anywhere. Suggestion? I don't think they would come after me, but I don't know what's the right thing to do.  Maybe I should just delete the csv files that contain their data and then release it as whatever license I want? If anyone wants to redo the analysis, they'd have to re-hit their API... but perhaps that's a small price to pay?

**Comment by stagas** [comment]
I think it's alright. Data are not covered by code licenses anyway, you could just state: License for data: unknown, contact hooktheory, License for the project: whatever.

From what I'm reading on their site, they're probably operating as a border case, as in using music clips under copyright's fair use clause to generate the data so they wouldn't try to protect them because it's not theirs to begin with. Looks like implicit public domain area.

**Comment by DataStrategist** [comment]
Pushed. GNU2... go nuts!  (What you gonna do?)
